name: Update, build and publish with Poetry

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update_build_publish:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: "false"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Update version
        run: sed -i 's/^version = .*/version = "${{github.ref_name}}"/' pyproject.toml
      
      - name: Build a binary wheel and a source tarball
        run: |
          pip install poetry
          poetry build

      - name: Commit and push changes
        run: |
          git checkout main
          git fetch origin
          git pull
          git add pyproject.toml ci_poetry/__init__.py
          git commit --amend --no-edit
          git push --force-with-lease
        
      - name: Publish to Test PyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      
      - name: Publish to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
